# Generated by Django 4.2.4 on 2023-08-30 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employees',
            fields=[
                ('emp_id', models.IntegerField(max_length=10, primary_key=True, serialize=False)),
                ('emp_name', models.CharField(max_length=255)),
                ('emp_des', models.CharField(max_length=255)),
                ('emp_contact', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'contacts',
            },
        ),
    ]
